spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
  mvc:
    path match:
      matching-strategy: ant_path_matcher


server:
  port: 9090


mybatis-plus:
  global-config: # 假删除
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml #扫描所有mybatis文件

files:
  upload:
    path: D:/Java/CompleteDesign/files/